### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Ciatronical** [karolyi/py3-ecrterm#1]
Ist es möglich den Zahlungsbetrag an das Terminal zu übertragen?

**Comment by karolyi** [comment]
Es ist Teil des ZVT-Protokolls, also ja.

**Comment by Ciatronical** [comment]
Ich habe leider keine Idee wie. Könntest du mir die Zeile in die in Testfile schreiben?

**Comment by karolyi** [comment]
Diese Method sollst du aufrufen:

https://github.com/karolyi/py3-ecrterm/blob/e884bcfe7c1ab4bfb0f2b5029dec4e5cdc8880f7/ecrterm/ecr.py#L272-L297

oder `Authorisation` selber.
