### ISSUE TITLE
Provide Reversal (06 30)

### ISSUE THREAD

**Issue by bwurst** [karolyi/py3-ecrterm#10]
I tried to implement Reversal as a packet type according to the ZVT documentation but I did not get it to work. Has someone tried that before?

When I do a Reversal ("Storno") at the device, I must give the "Trace-Nr" which is a decimal number printed on the receipt with 6 digits. The parameter for "Reversal" is named "receipt" and has 2 bytes length. Is this the "receipt" from the response to the Authorisation packet ("Beleg-Nr") or should one encode the Trace-Nr in any way to this 2 Bytes?

**Comment by karolyi** [comment]
See https://github.com/karolyi/py3-ecrterm/pull/9#issuecomment-733757725 please :)

**Comment by bwurst** [comment]
I have got Reversal to work on the py3 codebase. I did a few tests and think I can provide a pull request for Reversal against py3 soon.

**Comment by karolyi** [comment]
Cool, whenever you're ready. :)

Can you also tell if the py3 branch is production ready? That is, stable enough for use?
