### ISSUE TITLE
Unknown Status

### ISSUE THREAD

**Issue by imceZZ** [karolyi/py3-ecrterm#5]
i tried to run test_pt.py i got ip address from terminal menu and also the port, while the password also i changed but when i run the test_pt.py this is the result that i get:

`Unknown Status
> StatusEnquiry{05 01} *{'password': '1111'} **[]
< PacketReceived{80 00} **[]
< Completion{06 0F} *{'sw-version': '', 'terminal-status': 121} **[]
> PacketReceived{80 00} **[]
Unknown Status
> StatusEnquiry{05 01} *{'password': '1111'} **[]
< PacketReceived{80 00} **[]
< Completion{06 0F} *{'sw-version': '', 'terminal-status': 121} **[]
> PacketReceived{80 00} **[]
`

this message is continuously going in terminal while when i stop the process with control + c then i get this: 

`^CTraceback (most recent call last):
  File "test_pt.py", line 30, in <module>
    e.wait_for_status()
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/ecr.py", line 391, in wait_for_status
    status = self.status()
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/ecr.py", line 350, in status
    errors = self.transmit(StatusEnquiry(self.password))
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/ecr.py", line 373, in transmit
    transmission = self.transmitter.transmit(packet)
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/_transmission.py", line 92, in transmit
    ret = self._transmit(packet, self.last_history)
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/_transmission.py", line 57, in _transmit
    success, response = self.transport.send(packet)
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 120, in send
    return self.receive()
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 171, in receive
    data = self._receive()
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 159, in _receive
    data, length = self._receive_length()
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 146, in _receive_length
    data = self._receive_bytes(length=3)
  File "/Users/neim.elezi/Desktop/py3-ecrterm/ecrterm/transmission/transport_socket.py", line 130, in _receive_bytes
    chunk = self.sock.recv(length - recv_bytes)
KeyboardInterrupt
`

**Comment by accordioff** [comment]
Hi,

your status code is not covered in the current ZVT protocoll (v13.08). However, the terminal manufacturer may have additional status codes. Please have a look in the manufacturers documentation for additional commands, status and error information.
If you have a brand new PT out of the box, there are some tasks you have to do. Depending on your setup/application this might be:

1. Internet connection: As you can communicate with the PT, please check the router settings that might prevent outbound communication.

2. Setup Terminal-ID: In my case the TID was a necessity. Your terminal manufacturer sould be able to give you a setup software which allows you to change TID, network setup and testing environment. That's a good starting point.

If you are fine your PT should not show any orange or red LED status.

Hope that helps to get started.

**Comment by karolyi** [comment]
@imceZZ, did the above comment help you? I'd like to close this issue.

**Comment by imceZZ** [comment]
@karolyi to be honest I switched to Node Js and I was able to connect to the terminal and to send amount but I am facing other problem in the end of the transaction I receive this message **Transaction Declined From ECR** maybe you can suggest me something about this or can i have your email or SKYPE to contact you.

**Comment by karolyi** [comment]
Not sure I can help you there, especially with NodeJS.

You should watch for some kind of an error code, and I'd also look into if the terminal is able to process the card you're trying, because I've had that problem in the past too.

Since you don't use this module, I'm closing this issue.

**Comment by imceZZ** [comment]
What I read from their documentation they are saying that I should handle receipt-printout have you handled this receipt-printout if yes can you help me with this.
This is the pdf that I read: [LINK](https://www.terminalhersteller.de/pdf/PA00P015_13.08_en.pdf)

Best regards.
